version: "3.8"
services:
  app:
    build: .
    image: usvisa-fr:latest
    environment:
      - DEBUG=false
      - USVISA_USERNAME
      - USVISA_PASSWORD
    volumes:
      - ./APPOINTEMENTS_CHANGELOG.md:/usvisa-fr/APPOINTEMENTS_CHANGELOG.md
